version: "3.9"
services:
  postgres:
    container_name: wildberries-postgres
    image: postgres
    environment:
      POSTGRES_DB: "wildberries"
      POSTGRES_USER: "wildberries"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data

