version: "3.9"
services:
  postgres:
    container_name: wildberries-postgres
    image: postgres
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming
    container_name: nats_streaming
    ports:
      - "4222:4222"
      - "8222:8222"

